backend:
  name: git-gateway
  branch: content
# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: content

site_url: https://the-walks.netlify.app/admin/
media_folder: /static/medias/
editor:
  preview: false
show_preview_links: false


collections:
  - name: languages
    label: "Languages"
    folder: static/texts/
    slug: languageCode
    identifier_field: languageCode
    media_folder: /static/medias/
    fields:
      - label: Id
        name: id
        widget: string
      - label: Language Code
        name: languageCode
        widget: string
      - label: About
        name: body
        widget: markdown
      - label: Medias
        name: medias
        widget: list
        collapsed: false
        add_to_top: true
        field:
          name: walk
          widget: relation
          collection: walks
          search_fields: [title, body]
          value_field: id
          display_fields: ["{{title}}"]
  - name: walks
    label: "Walks"
    folder: static/texts/medias/
    slug: "{{language}}_{{id}}"
    identifier_field: id
    summary: "{{preTitle}} {{title}} {{afterTitle}} ({{language}}_{{id}})"
    fields:
      - label: Id
        name: id
        widget: string
      - label: Language
        name: language
        widget: relation
        collection: languages
        search_fields: [languageCode, title]
        value_field: languageCode
        display_fields: ["{{languageCode}} {{title}}"]
      - label: Short Title
        name: shortTitle
        widget: string
      - label: Pre Title
        name: preTitle
        widget: string
        required: false
      - label: Title
        name: title
        widget: string
      - label: After Title
        name: afterTitle
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
      - label: Listed
        name: listed
        widget: boolean
      - duration: Duration
        name: duration
        widget: string
      - label: Audio File
        name: srcUri
        widget: string
      - label: Walk icon
        name: iconUri
        widget: image
        media_library:
          config:
            multiple: false
            media_folder: /static/icons
      - label: User Prompts
        name: userPrompt
        widget: list
        fields:
          - label: Title
            name: title
            widget: text
          - label: Trigger Time (seconds)
            name: triggerTime
            widget: number
          - label: Loop Audio File
            name: srcUri
            widget: string
          - label: Actions
            name: actions
            widget: list
            required: false
            fields:
              - label: Title
                name: title
                widget: string
              - label: Action
                name: action
                widget: string
              - label: Post Action
                name: postAction
                widget: string
                required: false


        
  - name: news-index
    label: "News Index"
    folder: static/
    file: static/news_index.md
    identifier_field: news
    summary: Published news
    fields:
      - label: Published news
        name: news
        widget: list
        collapsed: false
        add_to_top: true
        summary: Post
        field:
          name: post
          widget: relation
          collection: news
          search_fields: [title, date, body]
          value_field: id
          display_fields: ["{{title}} - {{date | date('DD.MM.YY')}}"]
  - name: news
    label: News
    summary: "{{title}} - {{date | date('DD.MM.YY')}}"
    sortable_fields: ['date']
    folder: static/news
    create: true
    media_folder: /static/news/media/
    identifier_field: id
    slug: id
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "date"
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Image"
        name: "image"
        widget: "image"
        required: false

