local_backend: true
backend:
  name: git-gateway
  branch: api-v1

site_url: https://api-v1--the-walks.netlify.app/admin/
media_folder: /static/medias/
editor:
  preview: false
show_preview_links: false


collections:
  - name: languages
    label: "Languages"
    folder: static/texts/
    slug: "{{languageCode}}"
    identifier_field: languageCode
    media_folder: /static/medias/
    create: true
    fields:
      - label: Id
        name: id
        widget: string
      - label: Language Code
        name: languageCode
        widget: string
      - label: About
        name: body
        widget: markdown
        required: false
      - label: Credits
        name: credits
        widget: markdown
        required: false
      - label: Medias
        name: medias
        widget: list
        collapsed: false
        add_to_top: true
        required: false
        field:
          name: walk
          widget: relation
          collection: walks
          search_fields: [language, title, preTitle, afterTitle, shortTitle, body]
          value_field: "{{language}}_{{id}}"
          display_fields: ["{{language}} {{preTitle}} {{title}} {{afterTitle}} ({{language}}_{{id}})"]
  - name: walks
    label: "Walks"
    folder: static/texts/medias/
    slug: "{{language}}_{{id}}"
    identifier_field: id
    summary: "{{preTitle}} {{title}} {{afterTitle}} ({{language}}_{{id}})"
    create: true
    sortable_fields: [title, language, id]
    fields:
      - label: Walk icon
        name: iconUri
        widget: image
        required: false
        media_library:
          config:
            multiple: false
            media_folder: /static/icons
      - label: Id
        name: id
        widget: string
      - label: Language
        name: language
        widget: relation
        collection: languages
        search_fields: [languageCode, title]
        value_field: languageCode
        display_fields: ["{{languageCode}} {{title}}"]
      - label: Short Title
        name: shortTitle
        widget: string
      - label: Pre Title
        name: preTitle
        widget: string
        required: false
      - label: Title
        name: title
        widget: string
      - label: After Title
        name: afterTitle
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Credits
        name: credits
        widget: markdown
        required: false
      - label: Two person
        name: twoPerson
        widget: boolean
        required: false
      - label: Pen and Paper
        name: penPaper
        widget: boolean
        required: false
      - duration: Duration
        name: duration
        widget: string
        required: false
      - label: Listed
        name: listed
        widget: boolean
        default: true
      - label: Audio File
        name: srcUri
        widget: firebaseFile
      - label: User Prompts
        name: userPrompt
        widget: list
        required: false
        collapsed: true
        add_to_top: true
        fields:
          - label: Title
            name: title
            widget: text
          - label: Trigger Time (seconds)
            name: triggerTime
            widget: number
          - label: Loop Audio File
            name: srcUri
            widget: firebaseFile
          - label: Actions
            name: actions
            widget: list
            required: false
            default: []
            fields:
              - label: Title
                name: title
                widget: string
              - label: Action
                name: action
                widget: relation
                collection: userActions
                value_field: name
                search_fields: ["label", "name", "description"]
                display_fields: ["{{label}} - {{description}}"]
              - label: "Post Action (Default: Continue Walk)"
                name: postAction
                widget: relation
                collection: userActions
                value_field: name
                search_fields: ["label", "name", "description"]
                display_fields: ["{{label}} - {{description}}"]
                required: false
      - label: User Images
        name: userImages
        widget: userImages
        required: false
  - name: news-index
    label: "News Index"
    folder: static/
    file: static/news_index.md
    identifier_field: news
    summary: Published news
    fields:
      - label: Published news
        name: news
        widget: list
        collapsed: false
        add_to_top: true
        summary: Post
        field:
          name: post
          widget: relation
          collection: news
          search_fields: [title, date, body]
          value_field: id
          display_fields: ["{{title}} - {{date}}"]
  - name: news
    label: News
    summary: "{{title}} - {{date}}"
    sortable_fields: ['date']
    folder: static/news
    create: true
    media_folder: /static/news/media/
    identifier_field: id
    slug: "{{id}}"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - label: "Title"
        name: "title"
        widget: "string"
        required: false
      - label: "Place"
        name: "place"
        widget: "string"
        required: false
      - label: "Language"
        name: "language"
        widget: "string"
        required: false
      - label: "Date"
        name: "date"
        widget: "string"
        required: false
      - label: "Link"
        name: "linkUri"
        widget: "string"
        required: false
  - name: imprint
    identifier_field: languageCode
    label: Imprint
    summary: "{{languageCode}}"
    folder: static/imprint
    create: true
    slug: "{{languageCode}}"
    fields:
      - label: Language
        name: languageCode
        widget: relation
        collection: languages
        search_fields: [languageCode, title]
        value_field: languageCode
        display_fields: ["{{languageCode}} {{title}}"]
      - label: "Body"
        name: body
        widget: markdown
  - name: legal
    identifier_field: languageCode
    label: Data Protection & Legal notices
    summary: "{{languageCode}}"
    folder: static/legal
    create: true
    slug: "{{languageCode}}"
    fields:
      - label: Language
        name: languageCode
        widget: relation
        collection: languages
        search_fields: [languageCode, title]
        value_field: languageCode
        display_fields: ["{{languageCode}} {{title}}"]
      - label: "Agreements"
        name: agreements
        widget: object
        fields:
          - {label: First, name: one, widget: string}
          - {label: Second, name: two, widget: string}
          - {label: Third, name: three, widget: string}
          - {label: Fourth, name: four, widget: string}
      - label: "Body"
        name: body
        widget: markdown
  - name: voucherAnalytics
    label: "Voucher Analytics"
    summary: "{{dateStart}}_{{dateEnd}}"
    folder: static/analytics
    slug: "{{dateStart}}_{{dateEnd}}"
    create: true
    sortable_fields: [dateStart]
    fields:
      - label: "Start Date"
        name: dateStart
        widget: "datetime"
        format: "YYYY-MM-DD"
        time_format: false
      - label: "End Date"
        name: dateEnd
        widget: "datetime"
        format: "YYYY-MM-DD"
        time_format: false
      - label: "Get + Export CSV"
        name: voucherAnalytics
        widget: "voucherAnalytics"
        required: false
  - name: vouchers
    label: "Vouchers"
    label_singular: "Guest Venue"
    summary: "{{guestVenue}}"
    folder: static/vouchers
    slug: "{{guestVenue}}"
    create: true
    fields:
      - label: "Guest Venue"
        name: guestVenue
        widget: string
      - label: "Vouchers"
        name: vouchers
        widget: vouchers
        required: false
  - name: userActions
    label: "User Actions"
    folder: static/actions/
    slug: name
    hide: true
    fields:
      - {label: Label, name: label, widget: string}
      - {label: Name, name: name, widget: string}
      - {label: Description, name: description, widget: string}
  - name: userImages
    label: User Images
    folder: static/userImages
    summary: "User Images"
    create: false
    slug: "index"
    hide: true
    fields:
      - name: title
        hide: true
        widget: string
      - label: Walks
        name: walks
        widget: list
        allow_add: false
        fields:
          - label: Walk
            name: walk
            widget: userImages
