backend:
  name: git-gateway
  branch: content

site_url: https://the-walks.netlify.app/admin/
media_folder: static/icons

collections:
  - name: news
    label: News
    folder: static/news
    create: true
    media_folder: static/news/media
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Image"
        name: "image"
        widget: "image"
        required: false

