backend:
  name: github
  repo: rimini-protokoll/the_walks
  branch: content

site_url: https://the-walks.netlify.app/admin/
media_folder: static/icons


collections:
  - name: news-index
    label: "News Index"
    folder: static/
    file: static/news_index.md
    fields:
      - label: News
        name: news
        widget: list
        collapsed: false
        add_to_top: true
        field:
          name: news-item
          widget: relation
          collection: news
          search_fields: [title, date, body]
          value_field: id
          display_fields:
            - title
  - name: news
    label: News
    folder: static/news
    create: true
    media_folder: static/news/media
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - label: "Title"
        name: "title"
        widget: "string"
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Image"
        name: "image"
        widget: "image"
        required: false

